### ISSUE TITLE
Seems to work great on your server - how do I install on mine?

### ISSUE THREAD

**Issue by dgl-dev** [barelyhuman/mark#18]
# Question
Seems to work great on your server - how do I install on mine?

**Comment by barelyhuman** [comment]
It's a frontend only app, 
you can run it on anything that can serve html,css,js, 

```sh
npm i
npm build
```

and then add the `dist` files to your CDN/ behind an nginx/caddy proxy, it should work as expected

**Comment by barelyhuman** [comment]
I'll add detailed instructions on the readme

**Comment by barelyhuman** [comment]
https://github.com/barelyhuman/mark#development--self-hosting
Hope that helps, 
let me know if you need any more information :)

**Comment by dgl-dev** [comment]
All good, I just didn't see anything in the readme

Les Dunaway
770-490-7546 <http://voice.google.com/calls?a=nc,%2B17704907546>
