### ISSUE TITLE
Add copy as markdown option

### ISSUE THREAD

**Issue by Na-Cly** [barelyhuman/mark#22]
Hello, is it possible to add a menu button to copy the document as markdown instead of just downloading?

**Comment by barelyhuman** [comment]
You can just do a Ctrl C and it should copy the markdown, if it's not then that's a bug

**Comment by Na-Cly** [comment]
Hmm. I'll look into it, but when I copy on my Mac in brave browser it's grabbing just text itself.

**Comment by barelyhuman** [comment]
Looks like I discarded the shortcut at some point, re-added in #24
