### ISSUE TITLE
Saving content with code block doesn't save the code block

### ISSUE THREAD

**Issue by yeger00** [barelyhuman/mark#25]
Hello,
First of all thanks for maintaining the repository.
Second, I found an issue that when you refresh a page with code block in it (stated with <img width="34" alt="image" src="https://github.com/user-attachments/assets/4a2053e0-1eaf-4750-aad8-a7ec0827f6f5">), it is not being saved in the 
localstorage. 
The reason is that when changing from <img width="34" alt="image" src="https://github.com/user-attachments/assets/4fd7158d-fbba-45ad-8b33-e4f1b83d0709"> into the code block the <img width="34" alt="image" src="https://github.com/user-attachments/assets/ec5ea9c9-afaa-45f0-96ea-0ea873f60414"> are disappearing from the text.

I'm attaching a video with an example

https://github.com/user-attachments/assets/926e7fc4-4640-4ce9-9182-d37829e9857b

**Comment by barelyhuman** [comment]
Thanks for the report, will ping back once it's fixed

**Comment by barelyhuman** [comment]
Should be fixed in the current `pro` branch
