### ISSUE TITLE
Syntax highlight doesn't work

### ISSUE THREAD

**Issue by yeger00** [barelyhuman/mark#26]
Looks like syntax highlight doesn't work.
Here is an example image.

<img width="569" alt="image" src="https://github.com/user-attachments/assets/a0860436-c7ec-4528-9e08-929f39862b80">

**Comment by barelyhuman** [comment]
Thanks for the report, will ping back once it's fixed

**Comment by barelyhuman** [comment]
Fixed, should be a part of the new release
